repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.16.0
    hooks:
      - id: eslint
        args: [--fix]
        types: [javascript]
        additional_dependencies:
          - eslint@^9.16.0
          - globals@^15.12.10
          - neostandard@^0.11.9
